# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='file_attached',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
