# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=1000)),
                ('ai', models.FileField(blank=True, null=True, upload_to='ai_submit')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playerdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('0', 'AI1_wins'), ('1', 'AI2_wins'), ('2', 'tie')], max_length=1)),
                ('AI1_scorechange', models.IntegerField(default=0)),
                ('AI2_scorechange', models.IntegerField(default=0)),
                ('log', models.FileField(upload_to='logs')),
                ('AI1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai1_record', to='fight.Player')),
                ('AI2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai2_record', to='fight.Player')),
            ],
        ),
    ]
