# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='AI1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai1_record', to='fight.Player', verbose_name='ai1'),
        ),
        migrations.AlterField(
            model_name='record',
            name='AI2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai2_record', to='fight.Player', verbose_name='ai2'),
        ),
        migrations.AlterField(
            model_name='record',
            name='result',
            field=models.CharField(choices=[('1', 'AI2_wins'), ('0', 'AI1_wins'), ('2', 'tie')], max_length=1),
        ),
    ]
