# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-25 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0003_auto_20170225_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lasttime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to='logs'),
        ),
        migrations.AlterField(
            model_name='record',
            name='result',
            field=models.CharField(choices=[('0', 'AI1_wins'), ('1', 'AI2_wins'), ('2', 'tie')], max_length=1),
        ),
    ]
