# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0005_auto_20170227_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ai',
            field=models.FileField(blank=True, null=True, upload_to='submits'),
        ),
    ]
