# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0006_auto_20170227_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rpyNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
