# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0007_auto_20170227_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='rpyNumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
