# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0009_auto_20170301_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='log',
            field=models.CharField(default='', max_length=100),
        ),
    ]
