# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0010_auto_20170301_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
