# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0013_auto_20170301_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-score']},
        ),
        migrations.AddField(
            model_name='player',
            name='daily_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='last_reset_time',
            field=models.DateTimeField(default='2017-3-20 00:00:02'),
        ),
    ]
