# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170221_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='scores',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
