# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('replytime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='评论标题')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, verbose_name='摘要')),
                ('category', models.CharField(choices=[('1', '赛事公告'), ('2', '技术讨论'), ('3', 'bug汇报')], default=1, max_length=1)),
                ('priority', models.IntegerField(default=1000, verbose_name='优先级')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_attached', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('permissions', models.CharField(choices=[('1', '公开'), ('2', '登陆可见')], max_length=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_comment', to='forum.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
